### ISSUE TITLE
Issue with the ritual

### ISSUE THREAD

**Issue by Dredd893** [madgamer98/lichcraft2#6]
I've made the potion: 1* heart, 1* violet, 1* luminous, 1* noble sedge, 1* lloramor spine, 1* belladonna berries. 

- I put the amulet on at 12:00 am
- drink the potion.
- nothing at all happens.

I don't understand what is supposed to happen. Am I supposed to die? Ironically, I have 500 hp and the potion always fails even to kill me and stops me from opening the inventory screen once I've drunk it. Any suggestion?

Note that if I do the ritual at 11:00 it fails correctly (by telling me I did something wrong).

**Comment by Dredd893** [comment]
After trying and trying again, the ritual works. And now, after countless tries, it never fails. All I did differently was removing my health regenerating items.

**Comment by madgamer98** [comment]
Glad to hear that you were able to get it working. It seems like your health regeneration from the items was out healing the potions damage preventing you from hitting the low health trigger that completes the ritual. Perhaps the potion should remove regeneration buffs as well when you drink it to prevent that.

**Comment by Dredd893** [comment]
I reloaded now again the old savegame. The ritual is failing again. I removed the items. Suggestions?

**Comment by Dredd893** [comment]
Another "issue". When I revert back to lich form, I get Bounty:8000 even if I'm away from civilization. I don't think it should work like that.

**Comment by Dredd893** [comment]
Another issue: the game has become particularly crash prone after turning into a lich.

**Comment by Dredd893** [comment]
When casting the power ritual on the third day, it always fails. No matter what. But I think that one should be save proof, considering that all you have to do is 
- cast at 11:00 pm the spell
- wait 24 hours

The third day it fails because it says there is no full moon, even if the lunar thing alerts me there is a full moon.

**Comment by Dredd893** [comment]
When I ask to recruit followers to the npcs, they tend to forget it. Basically, it's a work of frustration.
